# Generated by Django 4.2.4 on 2024-04-09 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares_turisticos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugarturistico',
            name='popularidad',
            field=models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default='Baja', max_length=50),
        ),
    ]
