# Generated by Django 4.2.4 on 2024-04-09 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares_turisticos', '0002_lugarturistico_popularidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugarturistico',
            name='horario_funcionamiento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lugarturistico',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lugarturistico',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lugarturistico',
            name='precio_entrada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lugarturistico',
            name='sitio_web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lugarturistico',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
