# Generated by Django 4.2.4 on 2024-04-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares_turisticos', '0003_lugarturistico_horario_funcionamiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugarturistico',
            name='atracciones_cercanas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lugarturistico',
            name='horarios_amplios',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lugarturistico',
            name='precios_bajos',
            field=models.BooleanField(default=False),
        ),
    ]
