# Generated by Django 4.2.4 on 2024-04-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares_turisticos', '0004_lugarturistico_atracciones_cercanas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugarturistico',
            name='accesibilidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lugarturistico',
            name='aventura',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lugarturistico',
            name='gastronomia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lugarturistico',
            name='historia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lugarturistico',
            name='naturaleza',
            field=models.BooleanField(default=False),
        ),
    ]
