# Generated by Django 4.2.4 on 2024-04-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares_turisticos', '0005_lugarturistico_accesibilidad_lugarturistico_aventura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugarturistico',
            name='acceso_transporte_publico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lugarturistico',
            name='cantidad_atracciones_cercanas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lugarturistico',
            name='estacionamiento_disponible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lugarturistico',
            name='fotos_disponibles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lugarturistico',
            name='guias_turisticos_disponibles',
            field=models.BooleanField(default=False),
        ),
    ]
